# Streamlit secrets configuration file
# Add your secrets here, e.g. API keys, database credentials, etc.

[connections.neon_db]
# url = "postgresql://<user>:<password>@<host>/<database_name>"
url = "postgresql://neondb_owner:npg_PiSBl8Lwf2Nm@ep-calm-morning-a9voobwu-pooler.gwc.azure.neon.tech/neondb?sslmode=require&channel_binding=require"